### PR TITLE
[BREAKING] add groupcols and valuecols functions

### PR DESCRIPTION
**Pull request by bkamins**
`valuevars` function will be a useful complement to `groupvars` function.

If we have it we can actually deprecate `aggregate` already now, as then:
```
aggregate(df, :a, sum)
```
becomes
```
combine(gdf, valuevars(gdf) .=> sum)
```

@nalimilan In particular that adding broadcasting of `All` will not allow to deprecate `aggregate` as `All()` would include grouping columns which are skipped by `aggregate`.

If you think that some other name would be better please comment.

### CODE REVIEW

**Comment by nalimilan** [comment]
Good catch. It probably makes sense to add this only if we do deprecate `aggregate`.

About the name, I don't remember whether we discussed the choice of "vars" rather than "cols" or "keys" when `groupvars` was introduced.

**Comment by bkamins** [comment]
I thought you wanted to deprecate `aggregate` :) and this PR is exactly aimed to allow for this (but maybe users will find it useful also in other contexts?).

*Question 1* So - do we go for it?

Regarding the name - I do not think we discussed it.
Indeed probably `cols` would be better than `vars`, i.e. `groupcols` instead of `groupvars`. I can add such a deprecation in this PR.

*Question 2* Should we change `groupvars` to `groupcols`?

*Question 3* Would then `valuecols` be OK (i.e. do we think that non-grouping columns in `GroupedDataFrame` can be called value columns)?

**Comment by nalimilan** [comment]
> I thought you wanted to deprecate `aggregate` :) and this PR is exactly aimed to allow for this (but maybe users will find it useful also in other contexts?).

Yes but I thought *you* were hesitant about that. :-p

Actually I found the issue where we discussed `groupvars`: https://github.com/JuliaData/DataFrames.jl/issues/1704#issuecomment-459432627. So the name comes from dplyr, so the question is whether it's worth diverging from it to be consistent with our convention. I'd say yes.

"value columns" sounds goo, though I haven't thought too much about it. It's a bit similar to `stack`/`unstack`.

**Comment by bkamins** [comment]
I was hesitant about `aggregate`, but given the functionality we add I think we can drop it :smile:.

Yes `value` is similar to what `stack`/`unstack` produce, but I think it is OK (though not identical, as in the docs we call them "measure" variables).

But then maybe new names should be: `keycols` and `valuecols`. The reason is that now `GroupedDataFrame` supports key-value interface and in particular we support `keys` etc.?

**Comment by nalimilan** [comment]
I'm hesitant between `groupcols` and `keycols`. "keys" might not be very intuitive.

**Comment by bkamins** [comment]
The intuition is that now `groupby` essentially adds a key to a data frame. But I am OK with `groupcols` also. So - do you have a preference, or we should run a quick pool on #data on Slack?

**Comment by nalimilan** [comment]
Let's make a poll, it's always fun...

**Comment by JeffreySarnoff** [comment]
I have become disenamoured with method names that use "key" and do not open locks.

**Comment by bkamins** [comment]
I have reviewed `aggregate` and cleaned it up a bit. The conclusion is that I would keep it for corner-case uses (i.e. passing multiple anonymous functions), but not develop it further - just keep the functionality we have now.

**Comment by nalimilan** [comment]
> The conclusion is that I would keep it for corner-case uses (i.e. passing multiple anonymous functions), but not develop it further - just keep the functionality we have now.

Can you show examples of things that cannot be done with `combine`? It's going to be so powerful now that I wonder what's the point of having another limited function like `aggregate`.

**Comment by bkamins** [comment]
I will shortly open a PR deprecating `aggregate` per discussion and comment there.

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
