### PR TITLE
add travis on widows + x86 and remove AppVeyor

### LINKED ISSUE #1980: Drop AppVeyor in favour of TravisCI
What are peoples thoughts on dropping AppVeyor Windows builds in favour of using TravisCI Windows builds? Back in August TravisCI began supporting Julia Windows builds, [link](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187).

It seems that AppVeyor builds are [quite slow](https://ci.appveyor.com/project/nalimilan/dataframes-jl/history), and moving everything to TravisCI would centralize everything nicely.

### PR DESCRIPTION
**Pull request by bkamins**
Fixes #1980

Let us give it a shot.

CC @ararslan

### CODE REVIEW

**Comment by ararslan** [comment]
Note that `arch` is ignored for Mac builds since macOS hasn't supported anything but x86-64 in a long time, so every Mac build is duplicated here. I think we'll want to add something like
```yaml
matrix:
  exclude:
    - os: osx
      arch: x86
```
Also cool that they allow `arch` as a list now; they didn't used to.

**Comment by bkamins** [comment]
Thank you. I understand that we should delete AppVeyor integration for this repo after this PR is merged. Right?

**Comment by ararslan** [comment]
Yep. Looks like the AppVeyor build is running on @nalimilan's account, so he can turn off builds there.

**Comment by bkamins** [comment]
@ararslan - thank you.

@nalimilan - can you then please merge this PR and remove the integrations with AppVeyor if you are comfortable with this change (or comment if we have missed something 😄). Thank you!

**Comment by nalimilan** [comment]
Thanks. Having only one CI to handle is clearly simpler.

**Pull request merged**
