### PR TITLE
dcast instead of SDcols

### PR DESCRIPTION
**Pull request by tdhock**
using dcast is simpler so you may consider mentioning that, for example below
```r
> data.table(iris)[, unlist(lapply(.SD, function(x) c(max=max(x), min=min(x)))), .SDcols = c("Petal.Length", "Petal.Width") ]
Petal.Length.max Petal.Length.min  Petal.Width.max  Petal.Width.min 
             6.9              1.0              2.5              0.1 
> dcast(data.table(iris), . ~ ., list(max,min), value.var = c("Petal.Length", "Petal.Width"))
Key: <.>
        . Petal.Length_max Petal.Width_max Petal.Length_min Petal.Width_min
   <char>            <num>           <num>            <num>           <num>
1:      .              6.9             2.5                1             0.1
```

### CODE REVIEW

**Comment by bkamins** [comment]
What package does it come from?

**Comment by tdhock** [comment]
it comes from `data.table` which I thought was obvious since it is under the section about comparison with `data.table`, but to emphasize that you may change `dcast(...)` to `data.table::dcast(...)`

**Comment by bkamins** [comment]
The question was that I thought that `dcast` is not owned by data.table package, but indeed I checked the documentation and it is the way you say. Thank you!

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
