### PR TITLE
Update docs for new `describe`

### PR DESCRIPTION
**Pull request by pdeffebach**

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks!

This reminds me it would be nice to print `nothing` as the empty string to make this even nicer.

**Comment by pdeffebach** [comment]
For all of dataframes? Yeah I think thats a good idea.

**Comment by bkamins** [comment]
This should be clearly documented as otherwise there is a risk of user confusion (a milder version would be to print `nothing` using a different color like for `missing`).

**Comment by pdeffebach** [comment]
At the very least, it's super simple to just ad `try mean(col) catch "" end` in `describe`. That would definitely make the output prettier.

**Comment by bkamins** [comment]
Ah - now I understand. I agree with replacing `nothing` with `""` in describe as @pdeffebach explained.
I thought of a general printing of `nothing` when displaying `DataFrame` (but this is clearly a separate issue).

**Comment by bkamins** [comment]
Reflecting REPL behavior is convincing. 👍 for general behavior then (but let us document it).

**Comment by pdeffebach** [comment]
What about `missing`, then? We could do colored `m` and `n` for missing and nothing, respectively. Though I would agree that a blank being interpreted as `nothing` is more natural than, say, having another method of printing for `missing`

**Comment by pdeffebach** [comment]
Opened up a PR for printing an empty string instead of nothings. #1444 . But I think there is a better strategy than what I just wrote.

**Comment by nalimilan** [comment]
We've considered using various symbols to represent `missing` (in Slack discussions and at https://github.com/JuliaData/Missings.jl/pull/51#issuecomment-343761689), but it would be confusing to use a custom symbol if we don't defined the corresponding object equal to `missing`. Maybe we could agree on a standard symbol -- at the time of that PR, printing wasn't the most pressing issue.

**Pull request merged**
