### PR TITLE
Redirect https://dataframes.juliadata.org/ to https://dataframes.juliadata.org/stable/

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Comment by bkamins** [comment]
When will the change take effect?

**Comment by fredrikekre** [comment]
xref https://github.com/JuliaDocs/Documenter.jl/issues/937

**Comment by fredrikekre** [comment]
> When will the change take effect? Probably directly.

**Comment by bkamins** [comment]
This is what I thought but https://dataframes.juliadata.org/ now gives me 404.

**Comment by fredrikekre** [comment]
Thats the behavior before this PR. Probably some caching somewhere that hasn't been updated yet that you hit.

**Comment by nalimilan** [comment]
Seems to work now.

**Comment by ViralBShah** [comment]
This is the situation on every project. This is a good solution, that I'll try to propagate where I can.

**Pull request merged**
