### PR TITLE
make sure ByRow invokes generic map

### PR DESCRIPTION
**Pull request by bkamins**
fixes https://github.com/JuliaData/DataFrames.jl/issues/2957

TODO: add NEWS.md entry after #2981 is merged

### CODE REVIEW

**Comment by bkamins** [comment]
CI failure is unrelated (a traditional issue: out of memory on 32 bit machine)

**Comment by bkamins** [comment]
I am convinced we should make this change. New users should be provided with "safety first" approach. Advanced users that want speed can easily write `:x => x -> map(fun, x)`.

**Comment by bkamins** [comment]
@nalimilan - what do we do with this PR?

**Comment by nalimilan** [comment]
I guess we should go with it. Just a final check: do you have any idea whether this works with special array types like CUDA arrays?

**Comment by bkamins** [comment]
First - DataFrames.jl is most likely not very usable on GPU as:
```
┌ Warning: Performing scalar indexing on task Task (runnable) @0x000000000b3d2100.
│ Invocation of getindex resulted in scalar indexing of a GPU array.
│ This is typically caused by calling an iterating implementation of a method.
│ Such implementations *do not* execute on the GPU, but very slowly on the CPU,
│ and therefore are only permitted from the REPL for prototyping purposes.
│ If you did intend to index this array, annotate the caller with @allowscalar.
└ @ GPUArrays .julia\packages\GPUArrays\gkF6S\src\host\indexing.jl:56
```
when trying to display a `DataFrame` 😄.

Now regarding if:
```
invoke(map,
           Tuple{typeof(fun), ntuple(i -> AbstractVector, length(cols))...},
           fun, cols...)
```
works.

I have tested it and it works but is extremely slow, as it prints the same warning (and indeed it super slow) - in essence the generic `map` gets executed on CPU not GPU then.

However, even calling something like `map(x -> x+1, x_d)`, if `x_d` is `CuArray` is slow. What is fast is `x_d .+ 1`.

**Comment by bkamins** [comment]
@nalimilan - so what do we do here?

**Comment by nalimilan** [comment]
Sorry, I had missed your comment. I find this CUDA warning a bit silly, as it's perfectly OK for `show` to use slow indexing if that's only to print a few values at the REPL. I'm surprised that `map(x -> x+1, x_d)` is slow, but I guess that means nobody uses CUDA with DataFrames or we would have received complaints, so let's merge this.

**Comment by bkamins** [comment]
> I guess that means nobody uses CUDA with DataFrames or we would have received complaints,

This is what I would assume.

> so let's merge this.

Approval needed 😄

**Review by nalimilan — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
