### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aramirezreyes**
Adding DOI badge and citation info in the README to improve citation discoverability.

### CODE REVIEW

**Comment by DanielVandH** [comment]
Could also be good to include a .cff file so that it is linked in the sidebar (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

**Comment by navidcy** [comment]
It’s tricky to add CFF file that point to zenodo because they don’t get updated automatically with every new release.

**Comment by bkamins** [comment]
Thank you! Let us wait for otheres to comment for a few days. I have updated the PR to make it point to latest version on Zenodo (and thus removing the specific citation specification on the page for easier maintenance).

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
