### PR TITLE
Clarify that `sort!` permutes rows in-place

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you!

**Comment by bkamins** [comment]
Actually maybe we should make a copy? It would be faster. What do you think?

**Comment by nalimilan** [comment]
Other row-wise functions ending with a `!` seem to mutate column vectors in-place, right? IIRC we discussed this at some point. How much faster would copying be?

We could add a `copycols` argument to allow choosing which behavior to use, but that wouldn't be much more convenient than `df = sort(df, ...)`.

**Comment by bkamins** [comment]
I have now tested and it is not faster. I wonder why on Slack it was reported that `sort!` is slow then. Maybe for some specific column types?

**Pull request merged**
