### PR TITLE
Why not let `first(df)` have the same behaviour as `head(df)`?

### PR DESCRIPTION
**Pull request by xiaodaigh**

### CODE REVIEW

**Comment by xiaodaigh** [comment]
Oh. Is that what base is doing? Then forget

**Comment by bkamins** [comment]
@nalimilan we could allow `head` and `tail` though (I know they have been long deprecated). The `first(collection, n)` is defined only for `AbstractString` in Base. Having `firs` alias to `head` is not that bad I think. Same with `tail` and `last` (but this is not something crucial).

This is a similar discussion as with `size` and `nrow` and `ncol`.

**Comment by xiaodaigh** [comment]
OK. I like head tail ncol and nrow. They are concise and works well.

**Comment by bkamins** [comment]
And many people like them - that is why I would discuss to leave `head` and `tail`, although polluting name space with additional function names is not a very good practice in general.

**Comment by mkborregaard** [comment]
I agree - head, tail, ncol and nrow are useful aliases, well-known from other languages.

**Comment by bkamins** [comment]
Moving the discussion to https://github.com/JuliaData/DataFrames.jl/issues/1933 as this PR cannot be reopened.

**Pull request closed without merging**
