### PR TITLE
fix typo in `isdone`: df -> source

### PR DESCRIPTION
**Pull request by jrklasen**

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks! Do you have a minimal example to reproduce the bug? We should add it to the tests so that this kind of mistake doesn't happen again.

**Comment by jrklasen** [comment]
unfortunately not. I spotted this by reading the code in order to familiarize myself with DataStreams.

**Comment by jrklasen** [comment]
:), agreed

**Comment by nalimilan** [comment]
> Yeah, to test you could just do @test(Data.isdone(DataFrame(a=[1,2], b=[3,4])), 3, 3)

Can you make a PR to add it?

**Pull request merged**
