### PR TITLE
Switch from travis to GitHub Actions for CI testing

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by bkamins** [comment]
For me the set of test coverage looks good. We drop OSx but I think it is acceptable.

**Comment by bkamins** [comment]
Let us wait for @nalimilan to comment before making a final decision.

**Review by nalimilan — APPROVED** [review]
If that works it's fine with me!

**Comment by bkamins** [comment]
OK - let us wait for @quinnj to go back to this and merge if he is happy 😄.

**Review by bkamins — APPROVED** [review]

**Pull request merged**
