### PR TITLE
export Tables and Tables.columnindex

### PR DESCRIPTION
**Pull request by bkamins**
@quinnj and @nalimilan I have proposed to export `Tables` and `Tables.columnindex`. I am OK not to export `Tables.columnindex` if you feel it should not be exported and accessed with `Tables.` prefix.

### CODE REVIEW

**Comment by nalimilan** [comment]
I'm fine with exporting `columindex`, but should we reexport Tables?

**Comment by bkamins** [comment]
I was also thinking about it. The good thing is that Tables.jl exports nothing, so it does not pollute the namespace. But the benefit is minor (most users will not need it). Similarly here - I am also OK not to export it.

**Comment by nalimilan** [comment]
Probably better not export it then.

**Comment by bkamins** [comment]
OK - fixed

**Pull request merged**
