### PR TITLE
Prepare for 1.0 release

### PR DESCRIPTION
**Pull request by bkamins**
I want to allow:
* Missings.jl both 0.4.2 and 1.0 (this should be OK, except for `skipmissings` difference, but we do not use it: just re-export - @nalimilan - OK?)
* SortingAlgorithms.jl both 0.3 and 1.0 (this should be the same as discussed with @oxinabox)
* PrettyTables.jl both 0.12 and 1.0 (this should also be OK as discussed with @ronisbr)

to have less version synchronization issues on user's side.

I will make it non-draft when Missings.jl 1.0 and PrettyTables.jl 1.0 are released.

### CODE REVIEW

**Comment by bkamins** [comment]
and we need to wait for DataFramesMeta.jl 0.6.1. release as otherwise documenter will fail, cc @pdeffebach.

(and with this request we have everyone in the gang involved in this PR :)).

**Comment by bkamins** [comment]
This should be good for the review. After it is approved I will merge and make a release. Thank you!

**Comment by quinnj** [comment]
Hmmm, I don't understand the compat problem on 1.0; maybe we need to support `0.4.3` for Missings in this PR too? for compat w/ CategoricalArrays? Or in CategoricalArrays we need to support Missings 1.0?

**Comment by bkamins** [comment]
I do not understand the failure either as it works on my machine (anyway - I will bump CategoricalArrays.jl to support Missings.jl 1.0 and make a release there):
```
./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.5 (2019-09-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  (empty environment)

(v1.0) pkg> add DataFrames#bkamins-patch-1
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/JuliaData/DataFrames.jl.git`
 Resolving package versions...
 Installed Missings ─ v1.0.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [a93c6f00] + DataFrames v1.0.0 #bkamins-patch-1 (https://github.com/JuliaData/DataFrames.jl.git)
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [34da2185] + Compat v3.27.0
  [a8cc5b0e] + Crayons v4.0.4
  [9a962f9c] + DataAPI v1.6.0
  [a93c6f00] + DataFrames v1.0.0 #bkamins-patch-1 (https://github.com/JuliaData/DataFrames.jl.git)
  [864edb3b] + DataStructures v0.18.9
  [e2d170a0] + DataValueInterfaces v1.0.0
  [59287772] + Formatting v0.4.2
  [41ab1584] + InvertedIndices v1.0.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [e1d29d7a] + Missings v1.0.0
  [bac558e1] + OrderedCollections v1.4.0
  [2dfb63ee] + PooledArrays v1.2.1
  [08abe8d2] + PrettyTables v1.0.0
  [189a3867] + Reexport v1.0.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.4.2
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [9fa8497b] + Future 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
(v1.0) pkg> add CategoricalArrays
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [324d7699] + CategoricalArrays v0.9.5
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [324d7699] + CategoricalArrays v0.9.5
  [682c06a0] + JSON v0.21.1
  [e1d29d7a] ↓ Missings v1.0.0 ⇒ v0.4.5
  [69de0a69] + Parsers v1.1.0
  [856f2bd8] + StructTypes v1.7.1

(v1.0) pkg> test DataFrames
   Testing DataFrames
 Resolving package versions...
 Installed Adapt ─── v3.0.0
 Installed Unitful ─ v1.7.0
    Status `/tmp/tmpa7BhPz/Manifest.toml`
  [79e6a3ab] Adapt v3.0.0
  [324d7699] CategoricalArrays v0.9.5
  [861a8166] Combinatorics v1.0.2
  [34da2185] Compat v3.27.0
  [187b0558] ConstructionBase v1.1.0
  [a8cc5b0e] Crayons v4.0.4
  [9a962f9c] DataAPI v1.6.0
  [a93c6f00] DataFrames v1.0.0 #bkamins-patch-1 (https://github.com/JuliaData/DataFrames.jl.git)
  [864edb3b] DataStructures v0.18.9
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [59287772] Formatting v0.4.2
  [41ab1584] InvertedIndices v1.0.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.21.1
  [e1d29d7a] Missings v0.4.5
  [6fe1bfb0] OffsetArrays v1.6.2
  [bac558e1] OrderedCollections v1.4.0
  [69de0a69] Parsers v1.1.0
  [2dfb63ee] PooledArrays v1.2.1
  [08abe8d2] PrettyTables v1.0.0
  [189a3867] Reexport v1.0.0
  [a2af1166] SortingAlgorithms v0.3.1
  [856f2bd8] StructTypes v1.7.1
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.4.2
  [1986cc42] Unitful v1.7.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [9fa8497b] Future  [`@stdlib/Future`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
Running tests:
```

**Comment by bkamins** [comment]
https://github.com/JuliaData/CategoricalArrays.jl/commit/2fb2bc5ad4c2c127750fe8f68caeda4d7a6157e3#commitcomment-49813290

**Comment by bkamins** [comment]
All tests pass. @nalimilan - OK to merge?

**Review by quinnj — APPROVED** [review]

**Review by nalimilan — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you. Let us open a new chapter for DataFrames.jl starting tomorrow.

**Pull request merged**
