### PR TITLE
up version to 0.21.0

### PR DESCRIPTION
**Pull request by bkamins**
A final check before 0.21 release.

The plan is that ideally the next release is 1.0 and we do not include any breaking changes (the reality might turn out to be different).

What are key objectives to do after 0.21 release till 1.0 release:
1. documentation improvements
2. decouple DataFramesBase.jl to make the core much more lightweight
3. adding requested non-breaking functionality
4. find as many bugs as possible before 1.0 release

I would plan that we shall make 1.0 release in 3 to 6 months from now (depending how the things progress and the user feedback).

What I also will do after the release:
1. Write release notes on Discourse + Slack x-ref
2. Update DataFramesTutorial.jl

Thank you for working on the package!

### CODE REVIEW

**Comment by bkamins** [comment]
@nalimilan - CI passes cleanly except the known regex error on OSx nightly.

**Comment by bkamins** [comment]
Thank you! Let us just wait for @nalimilan to approve (and we need to merge https://github.com/JuliaData/CSV.jl/pull/602 and make a release of CSV.jl also to have everything in sync).

**Comment by quinnj** [comment]
@nalimilan is free to merge that PR and tag a new CSV release; so we can let him do all the synchronizing. (I'm happy to merge/tag as well if needed, just ping me on slack)

**Comment by bkamins** [comment]
This PR should be merged first, then I can make a release of DataFrames.jl, then CSV.jl needs to be updated (as it currently depends on DataFrames.jl also).

Thank you!

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
