### PR TITLE
Add .editorconfig and comment on GitHub Actions

### PR DESCRIPTION
**Pull request by jonas-schulze**
The `.editorconfig` is very close to the one I use personally. The lines about `end_of_line` and `charset` are best guesses. What do you think about it? If you want one but not the other, I'd be happy to split this PR.

### CODE REVIEW

**Comment by bkamins** [comment]
We use all the settings you have proposed, I am not sure if this is a standard to include this file in repositories.

@ararslan - can you please comment what you think?

**Comment by ararslan** [comment]
I agree, it does not seem to be standard for Julia package repositories to include this. Also why do actions need to be disabled on forks?

**Comment by jonas-schulze** [comment]
> I agree, it does not seem to be standard for Julia package repositories to include this.

To be honest, I haven't seen any Julia package to include an `.editorconfig`, but I think it would be really nice addition (and that there's no downside as it complies with the Style Guidelines).

> Also why do actions need to be disabled on forks?

Before opening #2157 I pushed all the changes of `JuliaData:master` to `jonas-schulze:master`, which a.o. added some GitHub Actions workflows. Then, today I got an email that a `Run failed: TagBot - master (d98b9be)`. It turned out that my fork had GitHub Actions enabled (maybe it's the default) and all the runs had failed with a time out (after 45min each).

I'd like to make other contributors aware, so that they are not as confused as I was. 🙃

I disabled Actions alltogether, but maybe someone only wants to disable third party ones (like TagBot). That's why the proposed change reads so general. An abstract of the above is in the commit message.

**Comment by bkamins** [comment]
Just to be clear I think both additions are not a problem, but @ararslan can you please decide as this PR is mostly related community and workflow standards (and here I am not an expert). Thank you!

**Comment by ararslan** [comment]
+1 to the comment about GitHub Actions, if that's something that was a source of confusion. I'm less enthused about the editor config file but I'm not opposed.

**Comment by bkamins** [comment]
So let us wait if some more JuliaData members will have an opinion here. Thank you both!

**Comment by nalimilan** [comment]
Which editors take this file into account by default?

**Comment by jonas-schulze** [comment]
bump 🙂

**Comment by jonas-schulze** [comment]
@bkamins bump 🙂

**Comment by bkamins** [comment]
This PR is pending the approval by @nalimilan.

**Comment by bkamins** [comment]
@nalimilan - I would merge this. It does not hurt to have it and it will prompt people what is the expected style, even if they do not use .editorconfig.

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
