### PR TITLE
added haskey in DataFrameRow

### PR DESCRIPTION
**Pull request by LeoK987**

### CODE REVIEW

**Comment by LeoK987** [comment]
Issue #1543

**Comment by nalimilan** [comment]
Thanks. Can you add a test too?

**Comment by LeoK987** [comment]
test added

**Comment by LeoK987** [comment]
Didn't know about negative test.  Thank you @nalimilan

**Comment by bkamins** [comment]
I guess we can merge it for now, but in the long term `haskey` for `DataFrame` should be removed (after we switch to row-based major approach), so maybe better to write `haskey(index(parent(df)), key)`?

OTOH it is useful to be able to efficiently check if a `DataFrame` has some column and `col in names(df)` is not efficient. @nalimilan Any thoughts on this?

**Comment by nalimilan** [comment]
> I guess we can merge it for now, but in the long term `haskey` for `DataFrame` should be removed (after we switch to row-based major approach), so maybe better to write `haskey(index(parent(df)), key)`?
> 
> OTOH it is useful to be able to efficiently check if a `DataFrame` has some column and `col in names(df)` is not efficient. @nalimilan Any thoughts on this?

Yes, that's a tough decision. We could keep `haskey` even if that's not consistent with the view of data frames as collections of rows. At least it's consistent with `getindex(df, col)`.

**Pull request merged**
