### PR TITLE
Support `append!`ing row-oriented tables

### PR DESCRIPTION
**Pull request by tkf**
This PR makes code such as `append!(DataFrame(), [(a=1,)])` work.

### CODE REVIEW

**Comment by bkamins** [comment]
The tests currently fail.

But even if they would pass why do we need the second branch?

**Comment by tkf** [comment]
> why do we need the second branch?

It looks like `append!` does not support row-oriented tables (checked with 1788d8a786868d41f19c8583ec7ae297f1172c07). Presumably, this is to make sure that it is copy-free?

```julia
julia> using DataFrames
       append!(DataFrame(), [(a=1,)])
ERROR: ArgumentError: It is not possible to construct a `DataFrame`from a `Vector{<:NamedTuple}` with `copycols=false`
Stacktrace:
 [1] DataFrame(::Array{NamedTuple{(:a,),Tuple{Int64}},1}; copycols::Bool) at /home/takafumi/.julia/dev/DataFrames/src/other/tables.jl:40
 [2] append!(::DataFrame, ::Array{NamedTuple{(:a,),Tuple{Int64}},1}) at /home/takafumi/.julia/dev/DataFrames/src/other/tables.jl:35
 [3] top-level scope at REPL[1]:2
```

I'll look into the test failure.

**Comment by tkf** [comment]
So the problem was that `push!(df, row)` does not support arbitrary row object specified by Tables.jl.  I see that there is a depwarn so maybe this is going to be fixed in the future?  For now, it seems to be using `Tables.columns` outside `DataFrame` constructor is the simplest solution.

For copy-free `append!` of row-oriented tables, I think you would need widening-based code like. [I implemented this already](https://github.com/tkf/BangBang.jl/blob/9cac31a559402fb8eee3ebd3c8d7879147d1d30f/src/dataframes_impl.jl#L49-L72) so I can turn this into a PR.  But it would be a somewhat non-trivial patch so I'm not sure what would be the best approach here.  (Unless there is some internal function that I can just call.)

**Comment by bkamins** [comment]
I think that your current proposal is a good temporary solution (maybe @quinnj might want to have a look at it).

I think there are the following things to be discussed additionally:
* do we want to allow `copycols` kwarg for the `DataFrame` and `DataFrame!` constructors in case they have to make a copy (i.e. it is impossible not to perform a copy) - currently we disallow it
* extension of `push!` to support arbitrary row object specified by Tables.jl. This I think can be discussed further in https://github.com/JuliaData/DataFrames.jl/issues/1982, as it adds to the wider design issue of `push!` that we currently discuss.

**Comment by tkf** [comment]
> * do we want to allow `copycols` kwarg for the `DataFrame` and `DataFrame!` constructors in case they have to make a copy (i.e. it is impossible not to perform a copy) - currently we disallow it

I think somewhat related question is: "does `copycols=false` mean to avoid _any_ kind of data copy?" (or maybe that's what you mean)  See `Tables.columns` at the end of this constructor:

https://github.com/JuliaData/DataFrames.jl/blob/1788d8a786868d41f19c8583ec7ae297f1172c07/src/other/tables.jl#L22-L33

So, `copycols=false` does not stop `Tables.columns` materializing ("copying") the columns.  However, this case is manually disallowed for:

https://github.com/JuliaData/DataFrames.jl/blob/1788d8a786868d41f19c8583ec7ae297f1172c07/src/other/tables.jl#L38-L42

This is the reason why `append!(DataFrame(a=[1]), (x for x in [(a=1,)]))` works but `append!(DataFrame(a=[1]), [(a=1,)])` does not.

**Comment by bkamins** [comment]
Agreed - I think we should make this consistent. My current feeling is that we should allow `copycols` always and say that if it is `false` we **try** not to copy, but we might copy it is not possible not to copy.

@nalimilan - any opinion on this (the other way would be to be always strict and guarantee that `copycols=false` fails if non-copying is not possible).

**Comment by nalimilan** [comment]
Makes sense.

**Comment by bkamins** [comment]
I have opened https://github.com/JuliaData/DataFrames.jl/pull/2004 for the `copycols` part of the discussion.

**Comment by quinnj** [comment]
To fix `append!(DataFrame(), [(a=1,)])`, I think the right correction is to define:
```julia
Base.append!(df::DataFrame, x::Vector{<:NamedTuple}) = append!(df, DataFrame(x; copycols=true))
```
This corresponds to the special-case `DataFrame` constructor we have for `Vector{<:NamedTuple}`.

**Comment by tkf** [comment]
@quinnj I guess #2004 is equivalent to that (with less code)?

**Comment by quinnj** [comment]
Yes, that looks right.

**Comment by nalimilan** [comment]
Closing since https://github.com/JuliaData/DataFrames.jl/pull/2004 fixed this in a different way. Thanks @tkf for catching this.

**Pull request closed without merging**
