### PR TITLE
handle empty args in subset

### PR DESCRIPTION
**Pull request by bkamins**
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3024

I have additionally corrected the docstring.

### CODE REVIEW

**Comment by bkamins** [comment]
@nalimilan this is also ready for review

**Review by nalimilan — COMMENTED** [review]
Looks good, but are there really uncovered lines?

**Comment by bkamins** [comment]
> Looks good, but are there really uncovered lines?

They are. I thought I have tested it but there are some more corner cases I have to cover. Added.

**Review by nalimilan — APPROVED** [review]

**Comment by bkamins** [comment]
thank you!

**Pull request merged**
