### PR TITLE
Use PrettyTables.jl's alignment anchor for numbers

### LINKED ISSUE #2605: Extremely slow show in the REPL
I made a silly mistake and obtained a `DataFrame` that takes forever to show in the REPL.
```julia
julia> using DataFrames, Dates

julia> function make_df()
           d0 = now()
           df = DataFrame(name=String[], time=DateTime[], status=Bool[])
           for i in 0:30*24*30*3
               d = d0 + Minute(i)
               for s in ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l")
                   #for chk in 1:3
                       push!(df, (name=s, time=d, status=rand(Bool)))
                   #end
               end
           end
           return df
       end;

julia> df = make_df();

julia> @time display(df)
[...]
  2.648168 seconds (7.65 M allocations: 463.344 MiB, 8.59% gc time, 99.82% compilation time)

julia> @time display(df)
[...]
  0.008935 seconds (7.24 k allocations: 7.006 MiB)

julia> df2 = transform(df, :time => x -> Date.(x) => :date);

julia> @time display(df2)
[...]
  67.131361 seconds (519.57 M allocations: 19.960 GiB, 4.10% gc time, 0.42% compilation time)

julia> @time display(df2)
[...]
  68.410671 seconds (518.96 M allocations: 19.924 GiB, 3.85% gc time)
```
Note the compile time percentage. I first thought it might be mostly compile time, but it takes as long in the second run (0% compile time).

### PR DESCRIPTION
**Pull request by ronisbr**
The alignment anchor was introduced in PrettyTables.jl v0.11. It allows
to define regexes that create anchors so that the text in the column is
aligned to them. Hence, all the code that were aligning the floating
points can be removed in favor of this new system.

Closes #2605

### CODE REVIEW

**Comment by bkamins** [comment]
CI fails

**Comment by bkamins** [comment]
apart from this - it looks fantastic (probably the CI problems are with having to change tests where floats are printed).

**Comment by ronisbr** [comment]
Hi @bkamins ,

The new code should produce exactly the same output as before. I tested locally and everything passes. Looking at the log, it seems that the CI failure is in another part:

```
test constructor with vectors: Test Failed at /home/runner/work/DataFrames.jl/DataFrames.jl/test/tables.jl:268
687
  Expression: DataFrame(Any[])
688
    Expected: ArgumentError
689
  No exception thrown
690
Stacktrace:
691
 [1] macro expansion at /home/runner/work/DataFrames.jl/DataFrames.jl/test/tables.jl:268 [inlined]
692
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
693
 [3] top-level scope at /home/runner/work/DataFrames.jl/DataFrames.jl/test/tables.jl:268
694
Test Summary:                 | Pass  Fail  Total
695
test constructor with vectors |   17     1     18
696
	FAILED: tables.jl
```

**Comment by ronisbr** [comment]
What seems really strange is that locally `DataFrame(Any[])` does throw an error:

```julia
julia> DataFrame(Any[])
ERROR: ArgumentError: type does not have a definite number of fields
Stacktrace:
 [1] fieldcount
   @ ./reflection.jl:729 [inlined]
 [2] buildcolumns
   @ ~/.julia/packages/Tables/z1juA/src/fallbacks.jl:206 [inlined]
 [3] columns
   @ ~/.julia/packages/Tables/z1juA/src/fallbacks.jl:262 [inlined]
 [4] DataFrame(x::Vector{Any}; copycols::Bool)
   @ DataFrames ~/tmp/DataFrames.jl/src/other/tables.jl:55
 [5] DataFrame(x::Vector{Any})
   @ DataFrames ~/tmp/DataFrames.jl/src/other/tables.jl:46
 [6] top-level scope
   @ REPL[2]:1
```

**Comment by ronisbr** [comment]
Found the problem, after upgrading to Tables v1.3.1, `DataFrame(Any[])` does not fail anymore.

**Comment by bkamins** [comment]
Yes - this is a change that @quinnj intended. I will open a separate PR only fixing this issue (to keep PRs separated logically) and can you then rebase after it is merged? Thank you!

**Comment by bkamins** [comment]
https://github.com/JuliaData/DataFrames.jl/pull/2609

**Comment by ronisbr** [comment]
> can you then rebase after it is merged?

Yes, sure!

**Comment by bkamins** [comment]
https://github.com/JuliaData/DataFrames.jl/pull/2609 is merged

**Comment by ronisbr** [comment]
Done! Let's see if everything passes now.

**Review by bkamins — APPROVED** [review]
Looks good (I assume you know what you are doing, as I understand we now just use the functionality of PrettyTables.jl). Thank you! Please merge when you are happy with the PR (as sometimes second thoughts come 😄).

**Comment by ronisbr** [comment]
> Looks good (I assume you know what you are doing, as I understand we now just use the functionality of PrettyTables.jl). Thank you! Please merge when you are happy with the PR (as sometimes second thoughts come 😄).

Thanks! Yes, the exactly same functionality was transferred to PrettyTables.jl. The modification is that instead searching for dots we can now use a regex to define the anchoring points. I will wait one day to process everything and then I will merge. :)

**Comment by ronisbr** [comment]
I reexecuted some examples of the docs and everything should be fine :)

**Pull request merged**
