### PR TITLE
bump prettytable to v2.0.0

### PR DESCRIPTION
**Pull request by Moelf**
we have to drop support for Julia pre 1.6 because that's what prettytable did

### CODE REVIEW

**Comment by bkamins** [comment]
This decision is still being discussed in https://github.com/JuliaData/DataFrames.jl/pull/3096.
We do not have a conclusion yet, but whatever we decide will be reflected in #3096.

**Comment by Moelf** [comment]
in any case this is the starting point of #3096? I don't understand the need to throw this PR in the trash can

**Comment by bkamins** [comment]
> I don't understand the need to throw this PR in the trash can

The policy of support of DataFrames.jl is that do not want to drop 1.0 support unless we have to.

**Comment by Moelf** [comment]
which is why this PR exists, to fix the breaking part that breaks DFs.jl?

**Comment by bkamins** [comment]
The history is a bit more complex:
* PrettyTables.jl has a better support for HTML output than DataFrames.jl currently has
* so we want to switch HTML rendering to PrettyTables.jl
* this in turn lead to many changes to PrettyTables.jl and @ronisbr when making these changes bumped the version of Julia required by PrettyTables.jl to 1.6

#3096 is a PR that synchronizes DataFrames.jl with new release of PrettyTables.jl (and its required version is currently bumped there).

That is why I also closed https://github.com/JuliaData/DataFrames.jl/pull/3130

**Comment by bkamins** [comment]
Or in other words - @ronisbr is a person that oversees integration of DataFrames.jl and PrettyTables.jl and it is safest when he commits changes related to this integration as he understands the consequences of such changes best.

**Pull request closed without merging**
