### PR TITLE
split and cobine paradigms and discussed about GroupedDataFrame

### PR DESCRIPTION
**Pull request by RohitRathore1**
split and combine paradigms and discussed GroupedDataFrame using `combine`, `select`, `transform`, `sort`, `nrow` and used some functionalities of statistics. It is mainly focused on *GroupedDataFrame*.

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you for the PR.

I can review this PR when other PRs related to documentation are finished.

I am also OK if you open several PRs but then combine them into one and then submit for a review.

Otherwise it is very hard for me to review three PRs that have inter-linked content.

**Comment by bkamins** [comment]
Hi - are you planning to work on this PR?

**Comment by RohitRathore1** [comment]
> Hi - are you planning to work on this PR?

Yes, i guess you can provide some comment on it.

**Comment by bkamins** [comment]
can you please merge it with `main` before reviewing? Also what is the position in the manual you propose to put it? Thank you.

**Comment by bkamins** [comment]
I am closing this PR due to inactivity (there is a risk that things get outdated). Please open a new updated PR if you would like to submit your proposal to change the documentation. Thank you!

**Pull request closed without merging**
